info:
 component: Edge Server

security:
  basic:
    enabled: false

spring.oauth2:
  client:
    accessTokenUri: http://localhost:8080/uaa/oauth/token
    userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
    clientId: makeurpicks
    clientSecret: secret
    scope: openid
  resource:
    jwt.keyUri: http://localhost:8080/uaa/token_key
    userInfoUri: http://localhost:8080/uaa/userinfo

logging:
  level: org.springframework.security=DEBUG
 
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: '*'
  routes:
    league:
      path: /leagues/**
      stripPrefix: false
    player:
      path: /players/**
      stripPrefix: false
    pick:
      path: /picks/**
      stripPrefix: false
    season:
      path: /seasons/**
      serviceId: season
      stripPrefix: false
    team:
      path: /teams/**
      serviceId: season
      stripPrefix: false
    week:
      path: /weeks/**
      stripPrefix: false
      serviceId: game
    game:
      path: /games/**
      stripPrefix: false
    leader:
      path: /leaders/**
      stripPrefix: false
    uaa:
      path: /uaa/**
      serviceId: player
