info:
 component: Edge Server
 
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: '*'
  routes:
    league:
      path: /league/**
    player:
      path: /player/**
    pick:
      path: /pick/**