spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_PORT_3306_TCP_ADDR:auth-db}/${MYSQL_ENV_MYSQL_DATABASE:player}?autoReconnect=true&useSSL=false
    username: ${MYSQL_USER:dbuser}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.jdbc.Driver


config:
   oauth2:
        ui-uri: http://34.209.187.83/
        admin-uri: http://34.209.187.83/admin/
        admin-ssluri: http://34.209.187.83/admin/
        localadmin-uri: http://34.209.187.83/admin/


eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
    status-page-url: http://delesio.com:9999/auth/info
    health-check-url: http://delesio.com:9999/auth/health
    home-page-url: http://delesio.com:9999/auth
 
         