
logging:
  level:
    org.springframework.security: DEBUG
security:
  sessions: ALWAYS
zuul:
  routes:
    ui:
      path: /ui/**
#      url: http://localhost:8081
    admin:
      path: /admin/**
#      url: http://localhost:8082
    league:
      path: /leagues/**
      stripPrefix: false
  #    url: http://localhost:9000
    player:
      path: /players/**
      stripPrefix: false
    pick:
      path: /picks/**
      stripPrefix: false
    season:
      path: /seasons/**
      serviceId: season
      stripPrefix: false
    team:
      path: /teams/**
      serviceId: game
      stripPrefix: false
    week:
      path: /weeks/**
      stripPrefix: false
      serviceId: game
    game:
      path: /games/**
      stripPrefix: false
    leader:
      path: /leaders/**
      stripPrefix: false