spring:
  application:
   name: gateway
  profiles:
    active: local
server:
  port: 8080
  
logging:
  level:
    org.springframework.security: INFO
    org.springframework.cloud.netflix: INFO
    com.netflix.zuul: INFO
    io.springbox.apigateway: DEBUG
    com.netflix.hystrix: DEBUG
    com.makeurpicks: DEBUG

security:
  oauth2:
    client:
      access-token-uri: ${vcap.services.auth-token.credentials.uri:http://localhost:9999/auth/oauth/token}
      user-authorization-uri: ${vcap.services.auth-authorize.credentials.uri:http://localhost:9999/auth/oauth/authorize}
      client-id: ui
      client-secret: secret
    resource:
      jwt:
        key-value: |
            -----BEGIN PUBLIC KEY-----
            MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNQZKqTlO/+2b4ZdhqGJzGBDlt
            b5PZmBz1ALN2YLvt341pH6i5mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE
            /myh1zM6m8cbL5cYFPyP099thbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26
            hL9dSAZuA8xExjlPmQIDAQAB
            -----END PUBLIC KEY-----

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${vcap.application.uris[0]:127.0.0.1}
    nonSecurePort: ${vcap.services.eureka-service.credentials.port:${server.port}}
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${random.value}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/


zuul:
#  host:
#    socket-timeout-millis: 5000
  routes:
    league:
      path: /leagues/**
      stripPrefix: false
  #    url: http://localhost:9000
    auth:
      path: /register/**
      stripPrefix: true
    pick:
      path: /picks/**
      stripPrefix: false
    season:
      path: /seasons/**
      serviceId: season
      stripPrefix: false
    team:
      path: /teams/**
      serviceId: game
      stripPrefix: false
    week:
      path: /weeks/**
      stripPrefix: false
      serviceId: game
    game:
      path: /games/**
      stripPrefix: false
    leader:
      path: /leaders/**
      stripPrefix: false
#    auth:
#      path: /register/auth/players/
#      strip-prefix: true

#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false
    

