security:
  oauth2:
    client:
      access-token-uri: http://auth.delesio.com:9999/auth/oauth/token
      user-authorization-uri: http://auth.delesio.com:9999/auth/oauth/authorize
      client-id: ui
      client-secret: secret
    resource:
      jwt:
        key-value: |
            -----BEGIN PUBLIC KEY-----
            MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNQZKqTlO/+2b4ZdhqGJzGBDlt
            b5PZmBz1ALN2YLvt341pH6i5mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE
            /myh1zM6m8cbL5cYFPyP099thbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26
            hL9dSAZuA8xExjlPmQIDAQAB
            -----END PUBLIC KEY-----

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
#    preferIpAddress: true
    status-page-url: http://delesio.com:8080/info
    health-check-url: http://delesio.com:8080/health
    home-page-url: http://delesio.com:8080/
