server:
  port: 8084
#security.user.password: dinesh
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    spring.rabbitmq.addresses: localhost:5672
  cloud:
    stream:
      bindings:
        season:
          group: season
          destination: leaguedata
          consumer:
            partitioned: true
            instance-index: 1
        league:
          group: league
          destination: leaguedata
          consumer:
            partitioned: true
            instance-index: 2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
#    url: jdbc:mysql://localhost:3304/league
#    username: root
#    password: admin123
    url: jdbc:mysql://localhost:3304/league
    username: root
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver