spring:
  application:
    name: league
  profiles:
    active: local    

server:
  port: 8081
  context-path: /leagues
security.user.password: testme
#security.user.password: dinesh

logging:
  level:
    com.makeurpicks: DEBUG
#    org.springframework.security: DEBUG