
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    spring.rabbitmq.addresses: localhost:5672
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_PORT_3306_TCP_ADDR:league-db}:${MYSQL_PORT_3306_TCP_PORT:3306}/${MYSQL_ENV_MYSQL_DATABASE:league}
    username: ${MYSQL_USER:dbuser}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.jdbc.Driver 
    dbcp:
      max-active:  5
      initial-size: 5
      max-idle: 2
      min-idle: 1
      test-on-borrow: true
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 3600000
      
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true