security:
  sessions: NEVER
#  oauth2:
#    client:
#      accessTokenUri: http://localhost:8080/uaa/oauth/token
#      userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
#      clientId: league
#      clientSecret: secret
#    resource:
#      userInfoUri: http://localhost:8080/uaa/user
#      
#logging:
#  level:
#    org.springframework.security: DEBUG