spring:
  application:
    name: league
  profiles:
    active: local    

server:
  port: 8081
  context-path: /leagues
security.user.password: testme
#security.user.password: dinesh

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    spring.rabbitmq.addresses: localhost:5672
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
#    url: jdbc:mysql://localhost:3304/league
#    username: root
#    password: admin123
    url: jdbc:mysql://localhost:3304/league
    username: dbuser
    password: password
    #url: jdbc:mysql://localhost:3306/cf_0619e413_5337_476d_98b7_2e1d996aa224
    #username: root
    #password: admin123
    driver-class-name: com.mysql.jdbc.Driver
security:
  oauth2:
    resource:
      jwt:
        key-uri: ${vcap.services.auth-token-key.credentials.uri:http://localhost:9999/auth/oauth/token_key}
  basic:
    enabled: false
  user:
    name: admin
#      userInfoUri: http://localhost:9999/auth/user

logging:
  level:
    com.makeurpicks: DEBUG
#    org.springframework.security: DEBUG