spring:
  application:
    name: league
  profiles:
    active: local    

server:
  port: 8081
  context-path: /leagues

security:
  oauth2:
    resource:
      jwt:
        key-uri: ${vcap.services.auth-token-key.credentials.uri:http://localhost:9999/auth/oauth/token_key}
  basic:
    enabled: false
  user:
    name: admin
#      userInfoUri: http://localhost:9999/auth/user

logging:
  level:
    com.makeurpicks: DEBUG
#    org.springframework.security: DEBUG