spring:
  application:
    name: league
  profiles:
    active: local    

server:
  port: 8081


logging:
  level:
    org.springframework.security: DEBUG
    log4j.logger.org.hibernate.SQL: DEBUG
    com.makeurpicks: DEBUG

#spring:
#  application:
#    name: league
#  profiles:
#    active: local    
#
#server:
#  port: 8081
#  context-path: /leagues
#
#logging:
#  level:
#    com.makeurpicks: DEBUG
#    org.springframework.security: DEBUG