spring:
  application:
    name: league
  profiles:
    active: local    

server:
  port: 8081
  context-path: /leagues



logging:
  level:
    com.makeurpicks: DEBUG
#    org.springframework.security: DEBUG