security:
  oauth2:
    client:
      useCurrentUri: false
      preEstablishedRedirectUri: http://34.209.187.83/admin/login
      access-token-uri: http://34.209.187.83/auth/oauth/token
      user-authorization-uri: http://34.209.187.83/auth/oauth/authorize
      logout-uri: http://34.209.187.83/auth/logout
      client-id: confidential
      client-secret: secret
    resource:
      jwt:
        key-value: |
            -----BEGIN PUBLIC KEY-----
            MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNQZKqTlO/+2b4ZdhqGJzGBDlt
            b5PZmBz1ALN2YLvt341pH6i5mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE
            /myh1zM6m8cbL5cYFPyP099thbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26
            hL9dSAZuA8xExjlPmQIDAQAB
            -----END PUBLIC KEY-----


config:
  oauth2:
    resourceURI: http://league:8081/leagues/user

    
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
    status-page-url: http://delesio.com:9000/admin/info
    health-check-url: http://delesio.com:9000/admin/health
    home-page-url: http://delesio.com:9000/admin   