#spring.profiles.active: google
#security:
#  basic:
#    enabled: false
#security:
#  oauth2:
#    client:
#      accessTokenUri: http://localhost:8080/uaa/oauth/token
#      userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
#      clientId: admin_portal
#      clientSecret: secret
#    resource:
#      jwt.keyUri: http://localhost:8080/uaa/token_key
#      userInfoUri: http://localhost:8080/uaa/userinfo

security:
  user:
    role: USER,ADMIN
#security:
#  oauth2:
#    client:
#      accessTokenUri: http://localhost:8080/uaa/oauth/token
#      userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
#      clientId: admin_portal
#      clientSecret: secret
#    resource:
#      userInfoUri: http://localhost:8080/uaa/user

#zuul:
#  ignoredServices: '*'
#  routes:
#    league:
#      path: /leagues/**
#      stripPrefix: false
#    player:
#      path: /players/**
#      stripPrefix: false
#    pick:
#      path: /picks/**
#      stripPrefix: false
#    season:
#      path: /seasons/**
#      serviceId: season
#      stripPrefix: false
#    team:
#      path: /teams/**
#      serviceId: game
#      stripPrefix: false
#    week:
#      path: /weeks/**
#      stripPrefix: false
#      serviceId: game
#    game:
#      path: /games/**
#      stripPrefix: false
#    leader:
#      path: /leaders/**
#      stripPrefix: false
      
logging:
  level:
    org.springframework.security: DEBUG
#    uaa:
#      path: /uaa/**
#      serviceId: player
#---
#
#spring:
#  profiles: google      
#
#spring.oauth2:
#  client:
#    accessTokenUri: https://accounts.google.com/o/oauth2/token
#    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
#    clientId: 217904051035-7rr1vdi0t42ltbka1r8g90nrk88jiki5.apps.googleusercontent.com
#    clientSecret: crnzxFjCBuK3F-EFvOq4Gnaj
#    scope: openid
#  resource:
#    jwt.keyUri: 
#    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo