server:
  port: 9000
  context-path: /admin

security:
  oauth2:
    client:
      access-token-uri: http://localhost:9999/auth/oauth/token
      user-authorization-uri: http://localhost:9999/auth/oauth/authorize
      client-id: confidential
      client-secret: secret
    resource:
      jwt:
        key-value: |
            -----BEGIN PUBLIC KEY-----
            MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNQZKqTlO/+2b4ZdhqGJzGBDlt
            b5PZmBz1ALN2YLvt341pH6i5mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE
            /myh1zM6m8cbL5cYFPyP099thbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26
            hL9dSAZuA8xExjlPmQIDAQAB
            -----END PUBLIC KEY-----
#        key-uri: "http://localhost:9999/auth/oauth/token_key"


config:
  oauth2:
#        clientID: confidential
#        clientSecret: secret
#        accessTokenUri: http://localhost:8081/oauth/token
#        userAuthorizationUri: http://localhost:8081/oauth/authorize
    resourceURI: http://localhost:8081/leagues/user
                
#security: 
#  user:
#    password: password
#    role: USER,ADMIN
#  oauth2:
#    sso:
#      home:
#        secure: false
#        path: /,/**/*.html
#    client:
#      accessTokenUri: http://localhost:9999/uaa/oauth/token
#      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
#      clientId: acme
#      clientSecret: acmesecret
#    resource:
#      userInfoUri: http://localhost:9999/uaa/user

#    
#  sessions: NEVER

zuul:
  routes:
    league:
      path: /leagues/**
      stripPrefix: false
    pick:
      path: /picks/**
      stripPrefix: false
    season:
      path: /seasons/**
      serviceId: season
      stripPrefix: false
    team:
      path: /teams/**
      serviceId: game
      stripPrefix: false
    week:
      path: /weeks/**
      stripPrefix: false
      serviceId: game
    game:
      path: /games/**
      stripPrefix: false
#    user:
#      path: /user/**
#      url: http://localhost:9999/uaa/user
            
logging:
  level:
    org.springframework.security: DEBUG
