server:
  port: 8082

logging:
  level:
    org.springframework.cloud: debug
    com.makeurpicks: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    region: default