spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    spring.rabbitmq.addresses: localhost:5672
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3305/game
    username: root
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver
    
security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:9999/auth/oauth/token_key
  basic:
    enabled: false
  user:
    name: admin
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#security:
#  oauth2:
#    client:
#      access-token-uri: http://localhost:9999/auth/oauth/token
#      user-authorization-uri: http://localhost:9999/auth/oauth/authorize
##      access-token-uri: http://localhost:9999/auth/oauth/token
##      user-authorization-uri: http://localhost:9999/auth/oauth/authorize
#      client-id: ui
#      client-secret: secret
#    resource:
#      jwt:
#        key-uri: http://localhost:9999/auth/oauth/token_key
#        key-value: |
#            -----BEGIN PUBLIC KEY-----
#            MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNQZKqTlO/+2b4ZdhqGJzGBDlt
#            b5PZmBz1ALN2YLvt341pH6i5mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE
#            /myh1zM6m8cbL5cYFPyP099thbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26
#            hL9dSAZuA8xExjlPmQIDAQAB
#            -----END PUBLIC KEY-----
#
#spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#  datasource:
#    url: jdbc:mysql://localhost:3305/game
#    username: root
#    password: admin123
#    driver-class-name: com.mysql.jdbc.Driver
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/